#!/bin/sh

#     __
#    / /  ___ ___ _    ____ _  ________
#   / _ \(_-</ _ \ |/|/ /  ' \/ __/ __/
#  /_.__/___/ .__/__,__/_/_/_/_/  \__/
#          /_/

# Launch auxillary applications.
pgrep -x polybar > /dev/null || cd "$HOME"/.config/polybar && polybar -r sfy &
pgrep -x sxhkd > /dev/null || sxhkd &

# Initialize workspaces.
bspc monitor -d 1 2 3 4

# Window rendering settings.
bspc config window_gap               4
bspc config border_width             1
bspc config split_ratio              0.50 
bspc config focus_follows_pointer	 true
bspc config gapless_monocle          true
bspc config focused_border_color     \#bd93f9
bspc config normal_border_color      \#251e28

# Desktop 2 is for web-browsers.
bspc rule -a firefox desktop=2 follow=on
bspc rule -a Chromium desktop=2 follow=on
bspc rule -a qutebrowser desktop=2 follow=on

# Desktop 3 is for messaging applications.
bspc rule -a TelegramDesktop desktop=3 follow=on
bspc rule -a discord desktop=3 follow=on
bspc rule -a element desktop=3 follow=on
bspc rule -a whatsdesk desktop=3 follow=on

# Display "normal" cursor everywhere.
xsetroot -cursor_name left_ptr &

