#!/bin/sh
#     __
#    / /  ___ ___ _    ____ _  ________
#   / _ \(_-</ _ \ |/|/ /  ' \/ __/ __/
#  /_.__/___/ .__/__,__/_/_/_/_/  \__/
#          /_/

launch_once() { pgrep --full "$1" > /dev/null || "$@" & }

# +TODO Make `polybar` work with `launch_once`.
pgrep -x polybar > /dev/null || cd "$HOME/.config/polybar" && polybar -r sfy &
launch_once sxhkd
launch_once telegram-desktop
launch_once firefox

# Display "normal" cursor everywhere.
xsetroot -cursor_name left_ptr &

# Initialize workspaces.
bspc monitor --reset-desktops     1 2 3

# Window rendering settings.
bspc config window_gap            4
bspc config border_width          1
bspc config split_ratio           0.5
bspc config focus_follows_pointer true
bspc config gapless_monocle       true
bspc config focused_border_color  \#bd93f9
bspc config normal_border_color   \#251e28

# Floating and portable kitty terminal.
bspc rule --add kitty:kitty_float \
                                  state=floating center=on \
                                  rectangle=1024x768+0+0

# Desktop 1 is for messaging applications.
bspc rule --add Element           desktop=1 follow=on
bspc rule --add TelegramDesktop   desktop=1 follow=on
bspc rule --add discord           desktop=1 follow=on
bspc rule --add whatsdesk         desktop=1 follow=on

# Desktop 2 is for web-browsers.
bspc rule --add Chromium          desktop=2 follow=on
bspc rule --add firefox           desktop=2 follow=on
bspc rule --add qutebrowser       desktop=2 follow=on

