#           _              
#     ___  (_)______  __ _ 
#    / _ \/ / __/ _ \/  ' \
#   / .__/_/\__/\___/_/_/_/
#  /_/                     

#################################
#       General Settings        #
#################################
vsync = true;
use-damage = true;
backend = "glx";
log-level = "info";
corner-radius = 9;

#################################
#            Blur               #
#################################
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 6;

#################################
#           Fading              #
#################################
fading = true;
fade-delta = 9;
fade-in-step = 0.1;
fade-out-step = 0.05;

#################################
#   Transparency / Opacity      #
#################################
inactive-opacity-override = true;
mark-ovredir-focused = true;
opacity-rule = [
    "90:class_g= 'kitty' && focused",
    "85:class_g= 'kitty' && !focused",
    "80:class_g= 'Rofi' && !focused",
];

#################################
#          Animations           #
#################################

# dccsillag/picom aka picom-animations-git is used instead of standard picom
# for animations.
animations = true;
animation-for-open-window = "zoom";
animation-stiffness = 300;
animation-dampening = 20;
animation-window-mass = 5;

