#!/bin/sh

#     __
#    / /  ___ ___ _    ____ _  ________
#   / _ \(_-</ _ \ |/|/ /  ' \/ __/ __/
#  /_.__/___/ .__/__,__/_/_/_/_/  \__/
#          /_/

# Launch auxillary applications.
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar sfy &

# Initialize workspaces.
bspc monitor -d 1 2 3 4 5

# Window render settings.
bspc config left_padding             12
bspc config right_padding            12
bspc config window_gap               10  
bspc config border_width             0
bspc config split_ratio              0.50 
bspc config focus_follows_pointer	   true
bspc config gapless_monocle          true

# Rules to display various applications in correct workspaces.
bspc rule -a firefox desktop=1 follow=on
bspc rule -a TelegramDesktop desktop=4 follow=on
bspc rule -a discord desktop=5 follow=on
bspc rule -a Pycalendar.py state=floating rectangle=300x300

# Makes it so that a "normal" cursor is displayed even when not placed on windows.
xsetroot -cursor_name left_ptr &
