#!/bin/sh

#     __
#    / /  ___ ___ _    ____ _  ________
#   / _ \(_-</ _ \ |/|/ /  ' \/ __/ __/
#  /_.__/___/ .__/__,__/_/_/_/_/  \__/
#          /_/

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5

########## Launch polybar
polybar main &

########## Window Settings
bspc config left_padding	        12
bspc config right_padding	        12
bspc config border_width            0
bspc config window_gap              10  
bspc config focus_follows_pointer	true
bspc config split_ratio             0.50 
bspc config gapless_monocle         true
bspc config border_radius	        10

######### Program settings ################
bspc rule -a firefox desktop=1 follow=on
bspc rule -a TelegramDesktop desktop=4 follow=on
bspc rule -a discord desktop=5 follow=on
bspc rule -a Pycalendar.py state=floating rectangle=300x300
#600x400+660+25

xsetroot -cursor_name left_ptr &
