;                __     __           
;     ___  ___  / /_ __/ /  ___ _____
;    / _ \/ _ \/ / // / _ \/ _ `/ __/
;   / .__/\___/_/\_, /_.__/\_,_/_/   
;  /_/          /___/                

; Ordering of directives for modules:
; 1. type
; 2. format
; 3. exec
; 4. label
; 5. animation
; 6. ramp
; 7. ws
; 8. padding
; 9. margin
; 10. colors
; 11. animation
; 12. other

[colors]
dark-pink = #251e28
dracula-pink= #ff79c6
dracula-yellow = #f1fa8c
dracula-orange = #ffb86c
dracula-purple = #bd93f9
dracula-green = #50fa7b

[bar/sfy]

; Set bar background color.
background = ${colors.dark-pink}

; Set the relative positioning of modules across the bar.
modules-left = decoration bspwm xwindow
modules-right = brightness volume layout datetime battery ovpn wi-fi

; Ensure bar doesn't overlap windows in fullscreen mode.
wm-restack = bspwm

; Set pointer to look like pointing hand when positioned over interactive components.
cursor-click = pointer

; Set bar length (expands to the right).
width = 98.35%

; Set bar height (expands down).
height = 36

; Set offset for the bar from the left side (moves bar to the right).
offset-x = 0.85%

; Set offset for the bar from the top (moves bar down).
offset-y = 5%

; Set the height of the underlines used to highlight workspaces.
line-size = 3

; Set the "roundness" of bar corners.
radius = 9

; Iosevka is used to render text.
font-0 = Iosevka:pixelsize=14;3

; Symbols Nerd Font is used to render icons.
; Icons for copy/paste could be found here: https://www.nerdfonts.com/cheat-sheet
font-1 = Symbols Nerd Font:pixelsize=18;3

; Sazanami Gothic is used to render japanese text.
font-2 = Sazanami Gothic:pixelsize=20;3

[module/decoration]
type = custom/text
content-foreground = ${colors.dark-pink}
content-background = ${colors.dracula-pink}
content-padding = 2

; Decoration for my bar with japanese text :)
; ユーダイモニア (yūdaimonia) means "eudaimonia".
content = ユーダイモニア

[module/bspwm]
type = internal/bspwm
format = <label-state>
label-focused = %icon%
label-occupied = %icon%
label-urgent = %icon%
label-empty = %icon%
ws-icon-0 =1;%{F#ff79c6}
ws-icon-1 =2;%{F#ff79c6}爵
ws-icon-2 =3;%{F#ff79c6}
ws-icon-3 =4;%{F#ff79c6}
label-focused-padding = 1
label-occupied-padding = 1
label-urgent-padding = 1
label-empty-padding = 1
ws-icon-foreground = ${colors.dracula-pink}
label-focused-underline = ${colors.dracula-pink}
label-separator = " "

[module/xwindow]
type = internal/xwindow
label = %title%
label-empty = "Desktop"
label-padding-left = 2
label-empty-padding-left = 2

; Set the maximum length of label.
label-maxlen = 71

[module/brightness]
type = internal/backlight
format = <ramp> <label>
label = %percentage%%
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
format-foreground = ${colors.dracula-yellow}
format-underline = ${colors.dracula-yellow}

; From polybar docs:
; Use the following command to list available cards:
; ls -1 /sys/class/backlight/
card = intel_backlight

[module/volume]
type = custom/script

; Temporary path until I finish my pull request and it gets merged.
exec = ~/repos/polybar-pulseaudio-control/pulseaudio-control.bash --color-muted "ffb86c" --icons-volume ",奔,墳," --icon-muted "ﱝ" --node-nickname "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink:ﰝ" --node-nickname "bluez_sink.04_CB_88_29_72_66.a2dp_sink:" --icons-bluetooth-battery "ﴆ,ﴇ,ﴈ,ﴉ,ﴊ,ﴋ,ﴌ,ﴍ,ﴎ,ﴅ" --hide-bluetooth-battery-level listen
label-margin = 2
label-foreground = ${colors.dracula-orange}
label-underline = ${colors.dracula-orange}
tail = true

[module/layout]
type = custom/script
; exec = echo -n " "; ~/repos/dotfiles/.scripts/layout_info.sh
exec = echo -n " "; ~/repos/dotfiles/.scripts/layout_info.sh
label-margin-right = 2
label-foreground = ${colors.dracula-green}
label-underline = ${colors.dracula-green}
interval = 0.01

[module/datetime]
type = custom/script

; Using custom command instead of `date` because default implementation does
; not work properly with the `%:::z` formatting sequence.
exec = echo -n " "; LC_ALL=C date +"%a %F %T UTC%:::z"
label-margin-right = 3
label-foreground = ${colors.dracula-purple}
label-underline = ${colors.dracula-purple}
interval = 1

[module/battery]
type = internal/battery
format-charging = <animation-charging>
format-discharging = <ramp-capacity>
format-full = 
format-low = <animation-low>
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 
animation-low-0 = 
animation-low-1 = 
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
format-charging-padding = 2
format-discharging-padding = 2
format-full-padding = 2
format-low-padding = 2
format-charging-foreground = ${colors.dark-pink}
format-discharging-foreground = ${colors.dark-pink}
format-full-foreground = ${colors.dark-pink}
format-low-foreground = ${colors.dark-pink}
format-charging-background = ${colors.dracula-pink}
format-discharging-background = ${colors.dracula-pink}
format-full-background = ${colors.dracula-pink}
format-low-background = ${colors.dracula-pink}
animation-charging-framerate = 200
animation-low-framerate = 500
low-at = 5

; From polybar docs:
; Use the following command to list batteries and adapters:
; ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC0
full-at = 95

[module/ovpn]
type = custom/script
exec = ~/repos/dotfiles/.scripts/openvpn_info.sh
label-padding-right = 2
label-foreground = ${colors.dark-pink}
label-background = ${colors.dracula-pink}
interval = 0.01

[module/wi-fi]
type = internal/network
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = 直
label-disconnected = 睊
label-connected-padding-right = 2
label-disconnected-padding-right = 2
label-connected-foreground = ${colors.dark-pink}
label-connected-background = ${colors.dracula-pink}
label-disconnected-foreground = ${colors.dark-pink}
label-disconnected-background = ${colors.dracula-pink}

; From polybar docs:
; Name of the network interface to display. You can get the names of the
; interfaces on your machine with `ip link`
; Wireless interfaces often start with `wl` and ethernet interface with `eno` or `eth`
interface = wlp0s20f3
