;                __     __           
;     ___  ___  / /_ __/ /  ___ _____
;    / _ \/ _ \/ / // / _ \/ _ `/ __/
;   / .__/\___/_/\_, /_.__/\_,_/_/   
;  /_/          /___/                

[colors]
grey-blue = #37456B
dark-blue = #111F39
dark-pink = #D75F87

[bar/main]
width = 98%
height = 36
offset-x = 1%
offset-y = 2%
radius = 9
background = ${colors.dark-blue}
line-size = 4
border-size = 2
border-top-size = 2
border-bottom-size = 4
border-left-size = 4
border-right-size = 4
padding-top = 4
font-0 = Fira Code Nerd Font:pixelsize=16;5
font-1 = Material Design Icons:size=20;5
font-2 = Sazanami Gothic:pixelsize=20;3
font-3 = Hack Nerd Font:pixelsize=20;5
font-4 = Font Awesome 6 Brands:pixelsize=20;5
modules-left = menu bspwm xwindow
modules-right = disk brightness volume layout wi-fi battery datetime datetime-bishkek
wm-restack = bspwm
cursor-click = pointer

[module/xwindow]
type = internal/xwindow
label = %title%
label-maxlen = 15
label-empty = "Desktop"
label-padding-left = 2
label-empty-padding-left = 2

[module/bspwm]
type = internal/bspwm
padding-top = 10
pin-workspaces = true
inline-mode = true
enable-click = true
format = <label-state>
ws-icon-0 =1;%{F#37456B}󰈹
ws-icon-1 =2;%{F#37456B}󰅭
ws-icon-2 =3;%{F#37456B}󰅭
ws-icon-3 =4;%{F#37456B}󰔁
ws-icon-4 =5;%{F#37456B}
label-focused = %icon%
label-focused-underline = ${colors.grey-blue}
ws-icon-foreground = ${colors.grey-blue}
label-focused-padding = 1
label-occupied = %icon%
label-occupied-padding = 1
label-urgent = %icon%
label-urgent-padding = 1
label-empty = %icon%
label-empty-padding = 1
label-separator = " "

[module/menu]
type = custom/text
content = ゆうかんさ
content-background = ${colors.grey-blue}
content-foreground = ${colors.dark-blue}
content-padding = 2

[module/disk]
type = internal/fs
interval = 25
mount-0 = /
label-mounted =   %percentage_used%%
label-mounted-padding-right = 2

[module/volume]
type = internal/pulseaudio
sink = alsa_outputci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink
use-ui-max = false
interval = 5
format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
label-muted  = ﱝ  %percentage%%
ramp-volume-0 = 
ramp-volume-1 = 奔
ramp-volume-2 = 墳
ramp-volume-3 = 
label-muted-foreground = ${colors.dark-pink}
format-volume-padding = 2
format-muted-padding = 2

[module/layout]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
label-layout = %icon%  %layout%
layout-icon-default = 
indicator-icon-0 = caps lock;ﰬ;ﰵ
label-indicator-on = %icon%
label-indicator-off = %icon%
label-indicator-on-foreground = ${colors.dark-pink}

[module/wi-fi]
type = internal/network
interface = wlp0s20f3
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = 直  %essid%
label-disconnected = 睊  NOCONN
label-disconnected-foreground = ${colors.dark-pink}
label-connected-padding = 2
label-disconnected-padding = 2

[module/battery]
type = internal/battery
full-at = 95
battery = BAT0
adapter = AC0
poll-interval = 1
format-charging = <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
label-charging =  %percentage%%
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
ramp-capacity-0-foreground = ${colors.dark-pink}
ramp-capacity-9-foreground = ${colors.dark-pink}

[module/datetime]
type = internal/date
interval = 1.0
date = "%{A1: .config/polybar/polybar-calendar/calendar.sh:}%a %Y-%m-%d M %T%{A}"
label =   %date%
label-padding-left = 2
label-padding-right = 1

[module/datetime-bishkek]
type = custom/script
interval = 1.0
exec = TZ=Asia/Bishkek date +"B %T"
label-padding-right = 2

[module/brightness]
type = internal/backlight
card = intel_backlight
enable-scroll = true
label = %percentage%%
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
format = <ramp>  <label>
