;                __     __           
;     ___  ___  / /_ __/ /  ___ _____
;    / _ \/ _ \/ / // / _ \/ _ `/ __/
;   / .__/\___/_/\_, /_.__/\_,_/_/   
;  /_/          /___/                

[colors]
dark-blue = #111F39
dark-pink = #D75F87
grey-blue = #37456B
light-purple = #9379F3

[bar/sfy]
background = ${colors.dark-blue}
modules-left = decoration bspwm xwindow
modules-right = brightness volume battery layout datetime datetime-bishkek wi-fi
wm-restack = bspwm
cursor-click = pointer
width = 98%
height = 36
offset-x = 1%
offset-y = 2%
line-size = 4
border-size = 2
radius = 9

; Fira Code Nerd Font is used to render text and block icons.
font-0 = Fira Code Nerd Font:pixelsize=16;5

; Material Design Icons is used to render app icons.
; Icons for copy/paste could be found here: https://fontawesome.com
font-1 = Material Design Icons:size=20;5

; Sazanami Gothic is used to render japanese text.
font-2 = Sazanami Gothic:pixelsize=20;3

; Font Awesome 6 Brands is used to render Discord icon. 
font-3 = Font Awesome 6 Brands:pixelsize=20;5

[module/decoration]
content-background = ${colors.grey-blue}
content-foreground = ${colors.dark-blue}
type = custom/text
content = ゆうかんさ
content-padding = 2

[module/bspwm]
ws-icon-foreground = ${colors.grey-blue}
label-focused-underline = ${colors.grey-blue}
type = internal/bspwm
label-focused = %icon%
label-occupied = %icon%
label-urgent = %icon%
label-empty = %icon%
label-focused-padding = 1
label-occupied-padding = 1
label-urgent-padding = 1
label-empty-padding = 1
label-separator = " "
format = <label-state>
ws-icon-0 =1;%{F#37456B}󰈹
ws-icon-1 =2;%{F#37456B}󰅭
ws-icon-2 =3;%{F#37456B}󰅭
ws-icon-3 =4;%{F#37456B}󰔁
ws-icon-4 =5;%{F#37456B}
padding-top = 10

[module/xwindow]
type = internal/xwindow
label = %title%
label-empty = "Desktop"
label-maxlen = 30
label-padding-left = 2
label-empty-padding-left = 2

[module/brightness]
type = internal/backlight
card = intel_backlight
label = %percentage%%
format = <ramp>  <label>
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 

[module/volume]
label-muted-foreground = ${colors.dark-pink}
type = internal/pulseaudio
label-muted  = ﱝ  %percentage%%
format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
format-volume-padding = 2
format-muted-padding = 2
ramp-volume-0 = 
ramp-volume-1 = 奔
ramp-volume-2 = 墳
ramp-volume-3 = 
use-ui-max = false

[module/battery]
ramp-capacity-0-foreground = ${colors.dark-pink}
ramp-capacity-9-foreground = ${colors.light-purple}
type = internal/battery
label-charging =  %percentage%%
format-charging = <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
battery = BAT0
adapter = AC0
full-at = 95

[module/layout]
label-indicator-on-foreground = ${colors.light-purple}
type = internal/xkeyboard
label-layout = %icon%  %layout%
label-indicator-on = %icon%
label-indicator-off = %icon%
label-layout-padding-left = 2
format = <label-layout> <label-indicator>
blacklist-0 = num lock
blacklist-1 = scroll lock
indicator-icon-0 = caps lock;ﰬ;ﰵ
layout-icon-default = 

[module/datetime]
type = internal/date
label =   %date%
label-padding-left = 2
label-padding-right = 1
date = "%{A1: .config/polybar/polybar-calendar/calendar.sh:}%a %Y-%m-%d M %T%{A}"

[module/datetime-bishkek]
type = custom/script
label-padding-right = 2
exec = TZ=Asia/Bishkek date +"B %T"

[module/wi-fi]
label-connected-foreground = ${colors.light-purple}
label-disconnected-foreground = ${colors.dark-pink}
type = internal/network
label-connected = 直
label-disconnected = 睊
label-connected-padding-right = 3
label-disconnected-padding-right = 3
format-connected = <label-connected>
format-disconnected = <label-disconnected>
interface = wlp0s20f3
